# configmap.yaml that I install into the jupyterhub namespace
# through a custom Helm chart that has a requirements.yaml file
# that in turn installs jupyterhub.
apiVersion: v1
kind: ConfigMap
metadata:
  name: hub-templates
data:
  {{- (.Files.Glob "files/etc/jupyterhub/templates/*").AsConfig | nindent 2 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: hub-external
binaryData:
  {{- $root := . }}
  {{- range $path, $bytes := .Files.Glob "files/static/external/*" }}
  {{ base $path }}: '{{ $root.Files.Get $path | b64enc }}'
  {{- end }}