---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: firefly
  namespace: firefly
spec:
  interval: 10m
  maxHistory: 3
  chart:
    spec:
      chart: firefly
      sourceRef:
        kind: GitRepository
        name: firefly
  install:
    remediation:
      retries: 3
      strategy: uninstall
  test:
    enable: false
