jupyterhub:
  cull:
    enabled: true
  scheduling:
    userPods:
      nodeAffinity:
        matchNodePurpose: require
    userScheduler:
      enabled: true
    podPriority:
      enabled: true
    userPlaceholder:
      enabled: false
      replicas: 0
  prePuller:
    hook:
      enabled: false
  hub:
    image:
      name: jupyterhub/k8s-hub
      tag: 0.11.1-n356.h2653b686
      pullPolicy: "Always"
    service:
      type: ClusterIP
    resources:
      requests:
        cpu: 300m
        memory: 1Gi
    allowNamedServers: true
    redirectToServer: false
    namedServerLimitPerUser: 2
  proxy:
    service:
      type: ClusterIP
  singleuser:
    storage:
      capacity: 20Gi
    defaultUrl: "/lab"
    extraEnv:
      JUPYTERHUB_SINGLEUSER_APP: "jupyter_server.serverapp.ServerApp"
      JUPYTER_ENABLE_LAB: "yes"
    podNameTemplate: "jupyter-{username}{servername}"
    image:
      name: jupyterhub/k8s-singleuser-sample
      tag: 0.11.1-n356.hceca1ebc
      pullPolicy: "Always"
    profileList:
      - display_name: "Default"
        description: "Standard Jupyterhub Single User sample environment"
        default: true
  ingress:
    enabled: true
