nginx-ingress-controller:
  enabled: true

jupyterhub:
  proxy:
    service:
      type: ClusterIP
  ingress:
    enabled: true
  singleuser:
    defaultUrl: "/lab"
    extraEnv:
      JUPYERHUB_SINGLEUSER_APP: "jupyter_server.serverapp.ServerApp"
    image:
      name: jupyterhub/k8s-singleuser-sample
      tag: 1.1.2-n020.h2568a1c3
  hub:
    config:
      Authenticator:
        admin_users:
          - firefly
      DummyAuthenticator:  # this is only appropriate for local environments
        password: firefly
      JupyterHub:
        authenticator_class: dummy
    allowNamedServers: true
    redirectToServer: false
    namedServerLimitPerUser: 2
    extraVolumes:
      - name: hub-templates
        configMap:
          name: hub-templates
      - name: hub-external
        configMap:
          name: hub-external
    extraVolumeMounts:
      - name: hub-templates
        mountPath: /etc/jupyterhub/templates
      - name: hub-external
        mountPath: /usr/local/share/jupyterhub/static/external
    extraConfig:
      templates: |
        c.JupyterHub.template_paths.insert(0, "/etc/jupyterhub/templates")