jupyterhub:
  cull:
    enabled: true
  scheduling:
    userScheduler:
      enabled: true
    podPriority:
      enabled: true
    userPlaceholder:
      enabled: false
      replicas: 0
  prePuller:
    hook:
      enabled: false
  singleuser:
    image:
      name: jupyterhub/k8s-singleuser-sample
      tag: 1.1.2-n020.h2568a1c3
  hub:
    config:
      Authenticator:
        admin_users:
          - firefly
      DummyAuthenticator:  # this is only appropriate for local environments
        password: firefly
      JupyterHub:
        authenticator_class: dummy
    db:
      type: sqlite-memory
    allowNamedServers: true
    redirectToServer: false
    namedServerLimitPerUser: 2
