nginx-ingress-controller:
  enabled: true

jupyterhub:
  proxy:
    service:
      type: ClusterIP
  ingress:
    enabled: true
    hosts:
      - localhost
  singleuser:
    image:
      name: jupyterhub/k8s-singleuser-sample
      tag: 1.1.2-n020.h2568a1c3
  hub:
    image:
      name: jupyterhub/k8s-hub
      tag: "1.1.3"
    config:
      JupyterHub:
        authenticator_class: nativeauthenticator.NativeAuthenticator
        admin_access: false
      Authenticator:
        admin_users:
          - firefly
      NativeAuthenticator:
        enable_signup: true
        minimum_password_length: 10
        check_common_password: true
        ask_email_on_signup: false
        allow_2fa: false
    allowNamedServers: true
    redirectToServer: false
    namedServerLimitPerUser: 2
    extraVolumes:
      - name: hub-templates
        configMap:
          name: hub-templates
      - name: hub-external
        configMap:
          name: hub-external
    extraVolumeMounts:
      - name: hub-templates
        mountPath: /etc/jupyterhub/templates
      - name: hub-external
        mountPath: /usr/local/share/jupyterhub/static/external
    extraConfig:
      templates: |
        c.JupyterHub.template_paths.insert(0, "/etc/jupyterhub/templates")
        
